

const productos = [
  { 
    id:1,
    nombre: "harina",
    precio: 150,
    img: "img/harina.jpg",
    cantidad:1,
  },
  {
    id:2,
    nombre: "leche",
    precio: 140,
    img: "img/leche.jpg",
    cantidad:1,
  },
  {
    id:3,
    nombre: "azucar",
    precio: 160,
    img: "img/azucar.jpg",
    cantidad:1,
  },
  {
    id:4,
    nombre: "manteca",
    precio: 400,
    img: "img/manteca.jpg",
    cantidad:1,
  },
  {
    id:5,
    nombre: "aceite",
    precio: 180,
    img:"img/aceite.jpg",
    cantidad:1,
  },
  {
    id:6,
    nombre: "levadura", 
    precio: 100,
    img:"img/levadura.jpg",
    cantidad:1,
  },
  {
    id:7,
    nombre: "sal",
    precio: 100,
    img:"img/sal.jpg",
    cantidad:1,
  },
  {
    id:8,
    nombre: "chocolate",
    precio: 500,
    img: "img/chocolate.jpg",
    cantidad:1,
  },
  {
    id:9,
    nombre: "dulce de leche", 
    precio: 300,
    img:"img/ddl.jpg",
    cantidad:1,
  },
  {
    id:10,
    nombre: "vainilla", 
    precio: 150,
    img:"img/vainilla.jpg",
    cantidad:1,
  },
  {
    id:11,
    nombre: "huevos", 
    precio: 380,
    img: "img/huevos.jpg",
    cantidad:1,
  },
];